name: Cory Allen Staats
favicon: null
layout_spectrum: 0.7200556644238532
typography_spectrum: 0.5375134008936584
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.04979569581337273
  lightness: 0.9521058343816549
  saturation: 0.7858029205817729
  rhythmicContrast: 0.13622819748707116
purpose: []
