name: Cory Allen Staats
favicon: null
layout_spectrum: 1
typography_spectrum: 0.35325
title: "Brandy Pete's Open Mic with Cory Allen Staats"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#161616'
    - '#ffffff'
    - '#5a5a5a'
    - '#a7a7a7'
    - '#dddddd'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.7858029205817729
  rhythmicContrast: 0.5
purpose: []
